# Site settings
title: keithxm23.github.io
email: keithxm23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  If you love soccer or Arsenal, say hi! :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://keithxm23.github.io" # the base hostname & protocol for your site
twitter_username: keithxm23
github_username:  keithxm23

# Build settings
markdown: kramdown

comments: true
