# Site settings
title: Keith's github page
email: keithxm23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This page is under construction
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: keithxm23
github_username:  keithxm23

# Build settings
markdown: kramdown
